[project]
src = "src"

[networks.contracts.price_feed] # default script 
deployer_script = "script/deploy_mocks.py"
abi = "mock_v3_aggregator"

[networks.contract.coffee]
deployer_script = "script/deploy.py"

[networks.anvil]
url = "http://127.0.0.1:8545"
default_account_name="anvil1"
save_to_db = true

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "default"
explorer_uri = "https://eth-sepolia.blockscout.com/"  
explorer_type = "blockscout"


#[networks.pyevm.contracts.price_feed]
#deployer_script = "script/deploy_mocks.py"

[networks.pyevm.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"
# deployer_script = "deploy_mocks.py"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
